"""Remediation §37 tests: curated failure examples and decision traces."""

from __future__ import annotations

import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from experiments.trustparadox_u.failure_examples import (  # noqa: E402
    ATTRIBUTION_SOURCES,
    CATEGORIES,
    MAX_EXAMPLES_PER_CATEGORY,
    build_failure_examples,
)

REQUIRED_EXAMPLE_FIELDS = (
    "category",
    "condition",
    "target_type",
    "candidate_text",
    "released_text",
    "detector_evidence",
    "policy_action",
    "oracle_label",
    "metric_contribution",
    "error_attribution",
)


class TestDeclaredProcedure:
    """§37 acceptance: selection follows a declared procedure."""

    def test_six_categories_declared(self) -> None:
        assert set(CATEGORIES) == {
            "false_negative_leakage",
            "false_positive_block",
            "partial_reconstruction",
            "incorrect_abstraction",
            "monitoring_failure",
            "trust_conditioned_difference",
        }

    def test_attribution_sources_distinguish_required_layers(self) -> None:
        assert {"detector", "history", "policy", "monitoring", "annotation"} <= set(
            ATTRIBUTION_SOURCES
        )

    def test_selection_procedure_declared_in_artifact(self) -> None:
        artifact = build_failure_examples()
        assert artifact["selection_procedure"].strip()
        assert artifact["privacy_statement"].strip()
        assert artifact["max_examples_per_category"] == MAX_EXAMPLES_PER_CATEGORY

    def test_all_categories_reported_even_when_empty(self) -> None:
        artifact = build_failure_examples()
        assert set(artifact["categories"]) == set(CATEGORIES)
        for info in artifact["categories"].values():
            assert "observed_count" in info
            assert "example_count" in info
            assert info["example_count"] <= MAX_EXAMPLES_PER_CATEGORY


class TestFailureExamplesContent:
    """Each example carries the §37 required fields and attribution."""

    def test_examples_carry_required_fields(self) -> None:
        artifact = build_failure_examples()
        seen = 0
        for info in artifact["categories"].values():
            for example in info["examples"]:
                seen += 1
                for field in REQUIRED_EXAMPLE_FIELDS:
                    assert field in example, f"missing {field} in {example['category']}"
        assert seen > 0

    def test_attributions_are_declared_sources(self) -> None:
        artifact = build_failure_examples()
        for info in artifact["categories"].values():
            for example in info["examples"]:
                assert example["error_attribution"] in ATTRIBUTION_SOURCES

    def test_example_counts_match_lists(self) -> None:
        artifact = build_failure_examples()
        for info in artifact["categories"].values():
            assert info["example_count"] == len(info["examples"])
            assert info["observed_count"] >= info["example_count"]

    def test_false_positive_blocks_report_zero_observed(self) -> None:
        artifact = build_failure_examples()
        info = artifact["categories"]["false_positive_block"]
        assert info["observed_count"] == 0
        assert info["note"]

    def test_trust_conditioned_difference_report_zero_observed(self) -> None:
        artifact = build_failure_examples()
        info = artifact["categories"]["trust_conditioned_difference"]
        assert info["observed_count"] == 0

    def test_monitoring_failures_only_under_monitored_conditions(self) -> None:
        artifact = build_failure_examples()
        for example in artifact["categories"]["monitoring_failure"]["examples"]:
            assert example["condition"] in {"full_mvp", "exact_only"}

    def test_selection_is_deterministic(self) -> None:
        first = build_failure_examples()
        second = build_failure_examples()
        for category in CATEGORIES:
            assert (
                first["categories"][category]["examples"]
                == second["categories"][category]["examples"]
            )


class TestGateRegistration:
    """The research-valid gate must enforce the §37 artifact."""

    def test_failure_examples_is_substantive_gate(self) -> None:
        from experiments.trustparadox_u.research_valid_gate import SUBSTANTIVE_GATES

        assert "failure_examples" in SUBSTANTIVE_GATES

    def test_check_failure_examples_passes_on_committed_artifacts(self) -> None:
        # Read-only: the artifact is regenerated by the reproduction
        # pipeline, never rewritten inside the test suite.
        from experiments.trustparadox_u.failure_examples import OUTPUT_PATH
        from experiments.trustparadox_u.research_valid_gate import check_failure_examples

        if not OUTPUT_PATH.exists():
            return  # artifact is produced by the reproduction cascade
        result = check_failure_examples()
        assert result["passed"], result.get("findings")
        assert result["num_categories"] == len(CATEGORIES)
